# Configuration pour auto-merge silencieux
# Copilot est le seul reviewer, merge automatique sans notification

version: 2

# Auto-merge activé pour tous les commits
auto_merge:
  enabled: true
  method: squash
  delete_branch_on_merge: true
  
# Reviewer automatique
reviewers:
  - copilot
    - claude  # optionnel
  
# Pas de notifications email
notifications:
  email: false
  
# Merge automatique sans approbation manuelle
require_review: false
require_approval: false

# Silent mode - pas de commentaires
silent: true
